!!python/object:argparse.Namespace
alpha: 0.2
data: ./data/data_except_bgw_400.npy
device: cuda:0
epochs: 1000
hidden_dim: 18
l:
- 1.0e-05
- 1.0e-05
- 0.0001
log_dir: ./runs/test/train/color_mlp/epochs=1000
lr: 0.1
num_heads: 5
wd: 0.0
